### Sign Up
POST http://127.0.0.1:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "8U%qz!v^io^P3uqN4#Ba",
  "confirmPassword": "8U%qz!v^io^P3uqN4#Ba",
  "firstName": "First",
  "lastName": "Last"
}

###

### Login
POST http://127.0.0.1:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "8U%qz!v^io^P3uqN4#Ba"
}

### List Rooms
GET http://127.0.0.1:8080/api/v1/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhdXRoIiwic3ViIjoidGVzdEBlbWFpbC5jb20iLCJleHAiOjE3MjM3OTM5MzksIm1hc2hyZXEtaWF0IjoxNzIzNzkyMTM5NzAxfQ.WekGo0-CHjZgow13oSPyW7eDTDi_FlyXfTfMPY82tEY

### List Rooms With Filters
GET http://127.0.0.1:8080/api/v1/rooms?startTime=2024-08-16T08:00:00&endTime=2024-08-16T08:15:00&numberOfPeople=2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhdXRoIiwic3ViIjoidGVzdEBlbWFpbC5jb20iLCJleHAiOjE3MjM3OTM5MzksIm1hc2hyZXEtaWF0IjoxNzIzNzkyMTM5NzAxfQ.WekGo0-CHjZgow13oSPyW7eDTDi_FlyXfTfMPY82tEY


### Create Booking
POST http://127.0.0.1:8080/api/v1/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhdXRoIiwic3ViIjoidGVzdEBlbWFpbC5jb20iLCJleHAiOjE3MjM3OTM5MzksIm1hc2hyZXEtaWF0IjoxNzIzNzkyMTM5NzAxfQ.WekGo0-CHjZgow13oSPyW7eDTDi_FlyXfTfMPY82tEY
Content-Type: application/json

{
    "startTime": "2024-08-16T14:00:00",
    "endTime": "2024-08-16T14:15:00",
    "name": "Important meeting",
    "description": "Meeting information",
    "numberOfPeople": 2
}

### Cancel Booking
DELETE http://127.0.0.1:8080/api/v1/bookings/bookingId
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhdXRoIiwic3ViIjoidGVzdEBlbWFpbC5jb20iLCJleHAiOjE3MjM3OTM5MzksIm1hc2hyZXEtaWF0IjoxNzIzNzkyMTM5NzAxfQ.WekGo0-CHjZgow13oSPyW7eDTDi_FlyXfTfMPY82tEY